InventoryApp/Models/DbContext/ApplicationContext.cs
namespace InventoryApp.Models.DbContext;
using Microsoft.EntityFrameworkCore;

public class ApplicationContext : DbContext
{
    public DbSet<User> Users { get; set; }
    public DbSet<Item> Items { get; set; }
    public DbSet<Room> Rooms { get; set; }

    public ApplicationContext() 
    {
        Database.EnsureCreated();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Server=localhost;Port=5432;Database=Inventory;Username=postgres;Password=2003;");
    }
}

InventoryApp/Models/ErrorViewModel.cs
namespace InventoryApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

InventoryApp/Models/Item.cs
namespace InventoryApp.Models;

public class Item
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Picture { get; set; } = "";
    public int Quantity { get; set; }
    public string RoomNumber { get; set; }
}

InventoryApp/Models/Room.cs
namespace InventoryApp.Models;

public class Room
{
    public int Id { get; set; }
    public string? RoomNumber { get; set; }
    public string? Picture { get; set; } = "";
}

InventoryApp/Models/User.cs
using System.Diagnostics.CodeAnalysis;

namespace InventoryApp.Models;

public class User
{
    public int Id { get; set; }
    
    public string? Email { get; set; }
    
    public string Password { get; set; }
    
}

InventoryApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using InventoryApp.Dtos;
using Microsoft.AspNetCore.Mvc;
using InventoryApp.Models;
using InventoryApp.Models.DbContext;
using Microsoft.EntityFrameworkCore;

namespace InventoryApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult AddItem()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddItem(AddItemDto addItemDto)
    {
        using (ApplicationContext db = new ApplicationContext())
        {
            var item = new Item {Name = addItemDto.Name,
                RoomNumber = addItemDto.RoomNumber,
                Quantity = addItemDto.Quantity};

            db.Items.Add(item);
            db.SaveChanges();
        }
        
        

        return RedirectToAction("Index");
    }

    public IActionResult Index()
    {
        using (ApplicationContext db = new ApplicationContext())
        {
            List<Room> rooms = db.Rooms.ToList();
            return View(rooms);
        }

        
    }
    
    public IActionResult Detail(string roomNum)
    {
        
        using (ApplicationContext db = new ApplicationContext())
        {
            List<Item> room = db.Items.Where(item => item.RoomNumber == roomNum).ToList();
            return View(room);    
        }
        
    }

    
    public IActionResult Delete(int id)
    {
        using (ApplicationContext db = new ApplicationContext())
        {
            Item item = db.Items.Where(item => item.Id.Equals(id)).FirstOrDefault();

            db.Items.Remove(item);

            db.SaveChanges();
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Edit(EditDto editItem)
    {


        using (ApplicationContext db = new ApplicationContext())
        {
            
            var item = db.Items.Where(item => item.Id == editItem.Id).FirstOrDefault();

            if (editItem.Name != "")
            {
                item.Name = editItem.Name;
            }
            
            if (editItem.Picture != "")
            {
                item.Picture = editItem.Picture;
            }
            
            if (editItem.Quantity != 0)
            {
                item.Quantity = editItem.Quantity;
            }
            Console.WriteLine(editItem.RoomNumber);
            Console.WriteLine(item.RoomNumber);
            if (editItem.RoomNumber != String.Empty)
            {
                item.RoomNumber = editItem.RoomNumber;
            }


            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        ViewData["Id"] = id;
        
        return View();
    }

    public class EditDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string RoomNumber { get; set; }
        public string Picture { get; set; }
    }
    
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

InventoryApp/Controllers/UserIdentityController.cs
using Microsoft.AspNetCore.Mvc;

namespace InventoryApp.Controllers;

public class UserIdentityController : Controller
{
    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }
    
    public IActionResult Logout()
    {
        if (Request.Cookies.ContainsKey("auth"))
        {
            Response.Cookies.Delete("auth");
            return Redirect("/Home/Index");
        }
        else
        {
            return Ok();
        }
    }
    
    [HttpPost]
    public IActionResult Login(string email, string password)
    {
        if (Request.Cookies.ContainsKey("auth"))
        {
            return Json(new {Message = "Already logged in" });
        }
        else
        {
            var cookiesOption = new CookieOptions();
            cookiesOption.Expires = DateTimeOffset.Now.AddDays(1);
            cookiesOption.Path = "/";
            Response.Cookies.Append("auth", "1234", cookiesOption);
            return Redirect("~/Home");
        }
        
        return Json(new { });
    }
}

InventoryApp/Views/Home/AddItem.cshtml
@{
    ViewBag.Title = "title";
}
<div align="center">
<h2>Add item</h2>
<form method="post">
    <div style="display: flex; flex-direction: column; width: 200px">
        <div>Name</div>
        <input type="text" name="name"/>
        <div>Room number</div>
        <input type="text" name="roomnumber"/>
        <div>Quantity</div>
        <input type="text" name="quantity"/>
        <input type="submit" value="Add item"/>
    </div>
</form>
</div>

InventoryApp/Views/Home/Detail.cshtml
@model List<Item>
@{
    ViewData["Title"] = "Details";
}

<!DOCTYPE html>

<html>
<body>
<div style="display: grid; grid-template-columns: 1fr 1fr">
      @foreach (var item in Model)
      {
          <div>
              <a href="/Home/Delete?id=@item.Id">Delete</a>
              <div>@item.Name Quantity: @item.Quantity</div> <a href="/Home/Edit?id=@item.Id">Edit</a>
              <div><img src="@item.Picture"/></div>
          </div>
      }
</div>
</body>
</html>

InventoryApp/Views/Home/Edit.cshtml
@model int

@{
    
}

<!DOCTYPE html>

<html>
<head>
    <title>Edit Item</title>
</head>
<body>
<div>
    <form method="post">
        @{
            <input name="id" type="hidden" value="@ViewData["Id"]"/>
        }
        <span>Name</span>
        <input name="name" type="text"/>
        <span>Picture URL</span>
        <input type="text" name="picture"/>
        <span>Room number</span>
        <input type="text" name="roomNumber"/>
        <span>Quantity</span>
        <input type="text" name="quantity"/>
        <input type="submit">
    </form>
</div>
</body>
</html>

InventoryApp/Views/Home/Index.cshtml
@model List<Room>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Inventory of AITU!</h1>
    <h2>Rooms:</h2>
    <table align="center" style="border: 1px solid black">
    @foreach (var room in Model)
    {
        <tr style="border: 1px solid black; padding: 5px">
            <th style="padding: 20px; "><img style="border-radius: 20px" width="400" height="200" src="@room.Picture"/></th>
            <td style="padding: 5px">
                <div>Room number: @room.RoomNumber <a href="/Home/Detail?roomNum=@room.RoomNumber">Go</a></div>
            </td>
        </tr>
    }
    </table>
</div>

InventoryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - InventoryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/InventoryApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InventoryApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navBar" class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul id="navbarId" class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UserIdentity" asp-action="Login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - InventoryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
<script>
    if (document.cookie.includes("auth=1234")) {
        const elem = document.getElementById("navbarId")
        const newElem = document.createElement("li")
        newElem.textContent = "Welcome, user!"
        newElem.className = "nav-item"
        elem.append(newElem)
        
        const elem1 = document.getElementById("navBar")
       
        const addButton = document.createElement("div")
        const addButton1 = document.createElement("a")
        addButton1.href = "Home/AddItem"
        addButton1.textContent = "Add Item"
        addButton.append(addButton1)
        elem1.append(addButton)
        
        const logoutButton = document.createElement("a")
        logoutButton.textContent = "Logout"
        logoutButton.id = "logoutButton"
        logoutButton.href = "/UserIdentity/Logout"
        const brake = document.createElement("div")
        brake.style.width = "20px"
        elem1.append(brake)
        elem1.append(logoutButton)
        
        const logOut = document.getElementById("logoutButton")
        
        
        }
    
</script>
</body>
</html>

InventoryApp/Views/UserIdentity/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>

<html>
<body>
<div>
    <h1 align="center">Login</h1>
    <form method="post">
        <div align="center" style="display: flex; flex-direction: column">
            <div>
                <div>Email:</div>
                <input type="text" value="" name="email"/>
            </div>
            <div>
                <div>Password</div>
                <input type="password" value="" name="password"/>
            </div>
            <div>
                <input type="submit" value="Login"/>
            </div>
        </div>
    </form>
</div>
</body>
</html>